export type WordList = {
  name: string
  description: string
  words: string[]
}

export const WORD_LISTS : Record<string, WordList> = {
  animals: {
    name: 'Animals',
    description: 'List of animals',
    words: [
      'Lion',
      'Elephant',
      'Dolphin',
      'Giraffe',
      'Eagle',
      'Kangaroo',
      'Panda',
      'Crocodile',
      'Penguin',
      'Gorilla',
      'Cheetah',
      'Wolf',
      'Zebra',
      'Tiger',
      'Rhino',
      'Shark',
      'Parrot',
      'Koala',
      'Octopus',
      'Flamingo',
    ],
  },
  popularSongs: {
    name: 'Popular Songs',
    description: '',
    words: [
      'Bohemian Rhapsody - Queen',
      'Imagine - John Lennon',
      'Smells Like Teen Spirit - Nirvana',
      'Billie Jean - Michael Jackson',
      'Stairway to Heaven - Led Zeppelin',
      'Like a Rolling Stone - Bob Dylan',
      'Hey Jude - The Beatles',
      'Hotel California - Eagles',
      'Sweet Child O\' Mine - Guns N\' Roses',
      'Rolling in the Deep - Adele',
      'Shape of You - Ed Sheeran',
      'Blinding Lights - The Weeknd',
      'Uptown Funk - Mark Ronson ft. Bruno Mars',
      'Thriller - Michael Jackson',
      'Lose Yourself - Eminem',
      'Shake It Off - Taylor Swift',
      'Wonderwall - Oasis',
      'Someone Like You - Adele',
      'Don\'t Stop Believin\' - Journey',
      'Old Town Road - Lil Nas X ft. Billy Ray Cyrus',
      'Hallelujah - Leonard Cohen',
      'Rolling Stones - Paint It Black - The Rolling Stones',
      'I Will Always Love You - Whitney Houston',
      'All of Me - John Legend',
      'Toxic - Britney Spears',
      'I Want to Hold Your Hand - The Beatles',
      'Shallow - Lady Gaga & Bradley Cooper',
      'Dancing Queen - ABBA',
      'Sorry - Justin Bieber',
      'Firework - Katy Perry',
      'Grenade - Bruno Mars',
      'Clocks - Coldplay',
      'Despacito - Luis Fonsi ft. Daddy Yankee',
      'Happy - Pharrell Williams',
      'Rolling in the Deep - Adele',
      'Take on Me - a-ha',
      'Purple Rain - Prince',
      'Radioactive - Imagine Dragons',
      'Havana - Camila Cabello',
      'Born to Run - Bruce Springsteen',
      'Superstition - Stevie Wonder',
      'No Woman, No Cry - Bob Marley',
      'Let It Be - The Beatles',
      'Take Me to Church - Hozier',
      'Thinking Out Loud - Ed Sheeran',
      'Bad Guy - Billie Eilish',
      'Seven Nation Army - The White Stripes',
      'Chandelier - Sia',
      'Skyfall - Adele',
      'Let Her Go - Passenger',
      'Blank Space - Taylor Swift',
      'Hotline Bling - Drake',
      'Stayin\' Alive - Bee Gees',
      'Creep - Radiohead',
      'Wrecking Ball - Miley Cyrus',
      'In the End - Linkin Park',
      'Sunflower - Post Malone & Swae Lee',
      'Closer - The Chainsmokers ft. Halsey',
      'Paparazzi - Lady Gaga',
      'Call Me Maybe - Carly Rae Jepsen',
      'Levitating - Dua Lipa ft. DaBaby',
      'We Will Rock You - Queen',
      'Heroes - David Bowie',
      'Viva La Vida - Coldplay',
      'Senorita - Shawn Mendes & Camila Cabello',
      'Livin\' on a Prayer - Bon Jovi',
      'My Heart Will Go On - Celine Dion',
      'Kiss - Prince',
      'Ain\'t No Mountain High Enough - Marvin Gaye & Tammi Terrell',
      'Tears Dry on Their Own - Amy Winehouse',
      'I Gotta Feeling - The Black Eyed Peas',
      'Wake Me Up - Avicii',
      'Love on Top - Beyoncé',
      'Lose Control - Missy Elliott',
      'Say You Won\'t Let Go - James Arthur',
      'Royals - Lorde',
      'We Belong Together - Mariah Carey',
      'Don\'t Speak - No Doubt',
      'Say My Name - Destiny\'s Child',
      'Tennessee Whiskey - Chris Stapleton',
      'Good as Hell - Lizzo',
      'Blowin\' in the Wind - Bob Dylan',
      'Mr. Brightside - The Killers',
      'Bad Romance - Lady Gaga',
      'Sex on Fire - Kings of Leon',
      'Savage Love - Jawsh 685 & Jason Derulo',
      'Time After Time - Cyndi Lauper',
      'I Don\'t Care - Ed Sheeran & Justin Bieber',
      'Eye of the Tiger - Survivor',
      'Can\'t Stop the Feeling! - Justin Timberlake',
      'Somebody That I Used to Know - Gotye ft. Kimbra',
      'When Doves Cry - Prince',
      'Believer - Imagine Dragons',
      'Watermelon Sugar - Harry Styles',
      'Rolling in the Deep - Adele',
      'One Dance - Drake',
      'Bad Habits - Ed Sheeran',
      'Stay - The Kid LAROI & Justin Bieber',
      'Rockstar - Post Malone ft. 21 Savage',
      'Iris - Goo Goo Dolls',
    ],
  },
}
